FROM courier-base

ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone
# COPY entrypoints/courier-mta /courier-mta
RUN cd /etc/courier; sed -i.dist 's/ESMTPDSTART=NO/ESMTPDSTART=YES/g' esmtpd

# Remove the PIDFILE argument, which should cause courier-tcpd to run in the foreground
RUN cd /usr/lib/courier/share; sed -i.dist 's/-pid=$PIDFILE"/"/;s%/usr/bin/mkdir -p `dirname $PIDFILE`%%' esmtpd
RUN tail /etc/courier/esmtpd
# ENTRYPOINT ["/usr/bin/echo", "Override the entrypoint"]
# ENTRYPOINT ["/bin/bash"]
# ENTRYPOINT ["/usr/bin/tail", "-f", "/dev/null"]
ENTRYPOINT ["/usr/lib/courier/sbin/esmtpd", "start"]
