FROM ubuntu:noble AS build-support-binaries

# Supporting binaries like the rendere, and maybe goss?

ENV TZ=UTC

RUN apt-get update && apt-get install -y tzdata
RUN ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone

RUN apt-get update 

COPY templater /templater
COPY install-scripts/packages.sh /tmp/packages.sh

RUN mkdir /export

RUN cd / && apt-get -y update && apt-get install -y curl && curl https://sh.rustup.rs -sSf | sh -s -- -y

RUN bash /tmp/packages.sh
# XXX this takes a lot of time to test
# RUN cd /templater && . "$HOME/.cargo/env" && cargo build && cp target/debug/render-template /export && chmod +x /export/render-template
RUN date > /export/render-template


# From now on, use new scripts/things to avoid re-building.

FROM scratch AS binaries
COPY --from=build-support-binaries /export /export


ENTRYPOINT ["/usr/bin/tail", "-f", "/dev/null"]
