FROM ghcr.io/pcn/mailbag-base:main
# Updated 2025-06-23 for entrypoint fixes

RUN cd /etc/courier; sed -i.dist 's/ESMTPDSTART=NO/ESMTPDSTART=YES/g' esmtpd

# The following should be in the entrypoints now
# mv target/acceptmailfor /etc/courier/esmtpacceptmailfor.dir/acceptmailfor
# RUN /usr/lib/courier/share/makeacceptmailfor

# The following should be in the entrypoints now
# COPY target/hosteddomains /etc/courier/hosteddomains
# RUN /usr/lib/courier/share/makehosteddomains


# Remove the PIDFILE argument, which should cause courier-tcpd to run in the foreground
RUN cd /usr/lib/courier/share; sed -i.dist 's/-pid=$PIDFILE"/"/;s%/usr/bin/mkdir -p `dirname $PIDFILE`%%' esmtpd && \
 echo "TLS_PROTOCOL=TLSv1.2++" >> esmtpd

# Debugging
RUN cd /usr/lib/courier/share && \
  echo "ESMTP_LOG_DIALOG=1" >> emstpd

COPY entrypoints/courier-mta /courier-mta
RUN chmod +x /courier-mta
ENTRYPOINT ["/courier-mta"]

