# Overridden by the build workflow with the base built in the same run.
ARG BASE_IMAGE=ghcr.io/pcn/mailbag:main
FROM ${BASE_IMAGE}
# Updated 2025-06-23 for entrypoint fixes

# /etc/courier/esmtpd-ssl is not configured here. The entrypoint renders it
# wholesale from esmtpd-mta-ssl.template on every start, so anything baked into
# the image at build time is overwritten before the service reads it. Every
# setting this used to append now lives in that template, including
# ESMTP_LOG_DIALOG, which is parameterised as mta_ssl.log_dialog.
#
# The appends were dead in a second way too: one wrote to `esmptd-ssl` and the
# other to `emstpd`, so they created stray files rather than touching any
# config. That is why enabling dialog logging here never produced any.



# The following should be in the entrypoints now
# COPY target/acceptmailfor /etc/courier/esmtpacceptmailfor.dir/acceptmailfor
# RUN /usr/lib/courier/share/makeacceptmailfor

# The following should be in the entrypoints now
# COPY target/hosteddomains /etc/courier/hosteddomains
# RUN /usr/lib/courier/share/makehosteddomains


# Remove the PIDFILE argument, which should cause courier-tcpd to run in the foreground
RUN cd /usr/lib/courier/share; sed -i.dist 's/-pid=$SSLPIDFILE //;s%/usr/bin/mkdir -p `dirname $SSLPIDFILE`%%' esmtpd-ssl   # && \
 # echo "TLS_PROTOCOL=TLSv1.2++" >> esmtpd-ssl


COPY entrypoints/courier-mta-ssl /courier-mta-ssl
RUN chmod +x /courier-mta-ssl
ENTRYPOINT ["/courier-mta-ssl"]
