FROM ghcr.io/pcn/mailbag-base:main
# Updated 2025-06-23 for entrypoint fixes

RUN cd /etc/courier; \
  echo "TLS_PROTOCOL=TLSv1.2++" >> imapd-ssl  && \
  echo 'IMAP_CAPABILITY="IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA AUTH=CRAM-MD5 AUTH=CRAM-SHA1 AUTH=CRAM-SHA256 IDLE"' >> imapd-ssl && \
  echo 'IMAP_CAPABILITY_TLS="$IMAP_CAPABILITY AUTH=PLAIN"' >> imapd-ssl

# TODO: test without, then try
#  IMAP_TLS_REQUIRED=1
# Remove the -pid argument, which should cause courier-tcpd to run in the foreground
# Also, the files are a bit different from the mta+msa, so this isn't totally copypasta
RUN cd /usr/lib/courier/share && \
  sed -i.dist 's/-pid=$SSLPIDFILE//;s/-start//g' imapd-ssl

COPY entrypoints/courier-imapd-ssl /courier-imapd-ssl
RUN chmod +x /courier-imapd-ssl
ENTRYPOINT ["/courier-imapd-ssl"]
