# support is the render-template binary
FROM ghcr.io/pcn/mailbag-support:main AS support
# export-stage is the packaged .debs for the courier components
FROM ghcr.io/pcn/mailbag-packages:main AS packages
FROM ubuntu:noble


COPY --from=packages /export /tmp/p

ENV TZ=UTC

RUN apt-get update && apt-get install -y tzdata
RUN ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone

RUN apt-get update  ; apt install -y less
RUN groupadd -g 300 vmail; useradd -M -r -d /opt/vmail -u 300 -g vmail vmail

RUN apt-get install -y locales bzip2 curl && echo "LANG=en_US.UTF-8" > /etc/default/locale

# RUN set -x; cd /tmp; mkdir p; cd p;
# curl -L https://github.com/pcn/mailbag-build-couriermta/releases/download/v01pre5/courier-v01pre5.tar.bz2 | tar -xjf - && \
RUN  ls /tmp/p
# Remove packages that we don't want, and install all of the remaining packages.
RUN cd /tmp/p; rm -f *web* *pop3* *mysql* *auth*pgsql* *auth*pipe* *ldap* *fax* *-dev* && \
  rm -f *mlm* && \
  apt install -y ./*.deb && \
  rm -f *.deb

COPY --from=support /export/render-template /render-template
RUN cd /etc/authlib; sed -idist 's/^authmodulelist="authuserdb /authmodulelist="authuserdb"  #/g' authdaemonrc
RUN chmod +x /render-template
COPY acceptmailfor.template /acceptmailfor.template
COPY hosteddomains.template /hosteddomains.template

ENTRYPOINT ["/usr/bin/tail", "-f", "/dev/null"]
