FROM ghcr.io/pcn/mailbag-base:main

# Oh, this is so much better than configuration management
# :rolls eyes:
RUN cd /etc/courier; \
  sed -i.dist 's/ESMTPDSTART=NO/ESMTPDSTART=YES/g;s/^BOFHNOEXPN=0/BOFHNOEXPN=1/g;s/^BOFHNOVRFY=0/BOFHNOVRFY=1/g;s/^ESMTPAUTH_TLS=""/ESMTPAUTH_TLS="PLAIN LOGIN"/g' esmtpd && \
  echo "TLS_PROTOCOL=TLSv1.2++" >> esmtpd && \
  echo "SYSLOGNAME=courieresmtpd-mta" >> esmtpd && \
  sed -i.dist 's/^BOFHCHECKDNS=1/BOFHCHECKDNS=0/g;s/^ESMTPDSTART=NO/ESMTPDSTART=YES/g' esmtpd-msa && \
  echo "SYSLOGNAME=courieresmtpd-msa" >> esmtpd-msa && \
  echo "ESMTP_LOG_DIALOG=2" >> esmtpd-msa && \
  echo "AUTH_REQUIRED=1" >> esmtpd-msa && \
  echo "ESMTPAUTH_TLS=\"PLAIN LOGIN CRAM-MD5 CRAM-SHA1 CRAM-SHA256\"" >> esmtpd-msa
  

# Remove the PIDFILE argument, which should cause courier-tcpd to run in the foreground
RUN cd /usr/lib/courier/share && \
  sed -i.dist 's/-pid=$PIDFILE"/"/;s%/usr/bin/mkdir -p `dirname $PIDFILE`%%' esmtpd 

COPY entrypoints/courier-courierd /courier-courierd
RUN chmod +x /courier-courierd
ENTRYPOINT ["/courier-courierd"]
