apiVersion: batch/v1
kind: CronJob
metadata:
  name: cert-renewal
  namespace: mailbag
  labels:
    app: mailbag
    component: cert-renewal
spec:
  schedule: "0 0 * * *"  # Daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: certbot
            image: certbot/certbot:latest
            args:
            - renew
            - --quiet
            volumeMounts:
            - name: letsencrypt
              mountPath: /etc/letsencrypt
            - name: context-json
              mountPath: /context.json
              subPath: context.json
              readOnly: true
            securityContext:
              runAsUser: 0  # Run as root for certbot
          volumes:
          - name: letsencrypt
            persistentVolumeClaim:
              claimName: courier-cert-pvc
          - name: context-json
            hostPath:
              path: /etc/mailbag/context.json
              type: File
          restartPolicy: OnFailure
