apiVersion: v1
kind: ConfigMap
metadata:
  name: mailbag-context
  namespace: mailbag
data:
  context.json: |
    {
      "mda": {
        "mail_path_host": "/vmail/example.com",
        "mail_path_container": "/vmail/example.com",
        "owner": "300",
        "mode": "0755"
      },
      "mta": {
        "dns_name": "mail.example.com",
        "tls_certfile": "/certs/live/example.com/fullchain.pem",
        "tls_keyfile": "/certs/live/example.com/privkey.pem",
        "service": "courier-mta",
        "accept_mail_for": ["example.com"],
        "courierd_path_host": "/home/mailbag/spool/courier",
        "courierd_path_container": "/var/spool/courier"
      },
      "imapd_ssl": {
        "dns_name": "imap.example.com",
        "tls_certfile": "/certs/live/example.com/fullchain.pem",
        "tls_keyfile": "/certs/live/example.com/privkey.pem",
        "service": "courier-imapd-ssl"
      },
      "mta_ssl": {
        "dns_name": "smtp.example.com",
        "tls_certfile": "/certs/live/example.com/fullchain.pem",
        "tls_keyfile": "/certs/live/example.com/privkey.pem",
        "service": "courier-mta-ssl",
        "accept_mail_for": ["example.com"],
        "courierd_path_host": "/home/mailbag/spool/courier",
        "courierd_path_container": "/var/spool/courier"
      },
      "msa": {
        "dns_name": "mail.example.com",
        "tls_certfile": "/certs/live/example.com/fullchain.pem",
        "tls_keyfile": "/certs/live/example.com/privkey.pem",
        "service": "courier-msa",
        "courierd_path_host": "/home/mailbag/spool/courier",
        "courierd_path_container": "/var/spool/courier",
        "base_syslog_name": "courieresmtpd",
        "syslog_name": "courieresmtpd-msa",
        "tls_protocol": "TLSv1.2++",
        "max_daemons": "40",
        "max_per_ip": "4",
        "auth_methods": "PLAIN LOGIN CRAM-MD5 CRAM-SHA1 CRAM-SHA256",
        "log_level": "2",
        "ulimit": "65536",
        "bofh_check_dns": "0",
        "tarpit": "1",
        "no_add_msgid": "1",
        "no_add_date": "1",
        "no_addr_rewrite": "0",
        "esmtp_log_dialog": "0",
        "auth_required": "0",
        "mail_user": "daemon",
        "mail_group": "daemon",
        "port": "smtp",
        "tls_certfile_internal": "/usr/lib/courier/share/esmtpd.pem",
        "tls_dhparams": "/usr/lib/courier/share/dhparams.pem",
        "tls_trustcerts": "/etc/ssl/certs/ca-certificates.crt",
        "tls_verifypeer": "NONE"
      },
      "userdb": {
        "directory": "/etc/authlib/userdb",
        "owner": "daemon",
        "mode": "0700"
      },
      "domain": {
        "name": "mail",
        "zone": "example.com"
      }
    }
  acceptmailfor.template: |
    {% for d in mta.accept_mail_for -%}
    {{ d }}
    {% endfor %}
  hosteddomains.template: |
    {% for d in mta.accept_mail_for -%}
    {{ d }}
    {% endfor %}
  esmtpd-base-msa.template: |
    ##VERSION: $Id: 7543161d83cfd2206785e5bac11e78a43935e57e-20240610193431$
    #
    # Base esmtpd configuration for MSA service
    # Generated from template using context.json
    #

    PATH=/usr/lib/courier/bin:/bin:/usr/bin:/usr/local/bin
    SHELL=/bin/bash

    # Base syslog name
    SYSLOGNAME={{ msa.base_syslog_name | default("courieresmtpd") }}

    # Enable ESMTP daemon
    ESMTPDSTART=YES

    # Hide EXPN and VRFY commands
    BOFHNOEXPN=1
    BOFHNOVRFY=1

    # TLS protocol version
    TLS_PROTOCOL={{ msa.tls_protocol | default("TLSv1.2++") }}

    # Connection limits
    MAXDAEMONS={{ msa.max_daemons | default("40") }}
    MAXPERIP={{ msa.max_per_ip | default("4") }}

    # Access file and PID file for makesmtpaccess
    ACCESSFILE={{ msa.access_file | default("/etc/courier/smtpaccess") }}
    PIDFILE={{ msa.pid_file | default("/var/spool/courier/tmp/esmtpd.pid") }}
  smtpaccess-default.template: |
    # Copyright 1998 - 2011 Double Precision, Inc.  See COPYING for
    # distribution information.
    #
    # Default access policies for courieresmtpd
    # Generated from template using context.json
    #
    # By default, enable relaying for localhost.

    127.0.0.1       allow,RELAYCLIENT
    :0000:0000:0000:0000:0000:0000:0000:0001        allow,RELAYCLIENT

    # Enable relaying for configured networks
    {% for network in msa.relay_networks | default(["10", "192.168"]) -%}
    {{ network }}       allow,RELAYCLIENT
    {% endfor -%}

    # Additional access rules
    {% if msa.access_rules -%}
    {% for rule in msa.access_rules -%}
    {{ rule.network }}       {{ rule.action }}
    {% endfor -%}
    {% endif -%}
  authdaemonrc.template: |
    ##VERSION: $Id$
    #
    # Copyright 1998 - 2007 Double Precision, Inc.  See COPYING for
    # distribution information.
    #
    # authdaemonrc created from authdaemonrc.dist by sysconftool
    #
    # Do not alter lines that begin with ##, they are used when upgrading
    # this configuration.
    #
    # This file configures authdaemond, the resident authentication daemon.
    #
    # Comments in this file are ignored.  Although this file is intended to
    # be sourced as a shell script, authdaemond parses it manually, so
    # the acceptable syntax is somewhat limited.  Multiline variable
    # contents, and other advanced shell features, are not supported.

    ##NAME: authmodulelist:2
    #
    # The authentication modules that are linked into authdaemond.  The
    # default list is installed.  You may selectively disable modules simply
    # by removing them from the following list.  The available modules you
    # can use are: authuserdb authpam authpgsql authldap authmysql authcustom authpipe

    authmodulelist="{{ userdb.auth_modules | default("authuserdb authpam") }}"

    ##NAME: authmodulelistorig:2
    #
    # This setting is used by Courier's webadmin module, and should be left
    # alone

    authmodulelistorig="{{ userdb.auth_modules_orig | default("authuserdb authpam authpgsql authldap authmysql authcustom authpipe") }}"

    ##NAME: daemons:0
    #
    # The number of daemon processes that are started.  authdaemond automatically
    # increases or decreases the number of daemon processes, but this is the
    # minimum number of daemon processes that are running at any given time.

    daemons={{ userdb.daemons | default("5") }}

    ##NAME: authdaemonvar:0
    #
    # authdaemond saves the process ID of the head daemon process in
    # $authdaemonvar/pid.  The logs are saved in $authdaemonvar/log (if authdaemond
    # is started by a non-root process, and if syslog is not used).

    authdaemonvar=/var/spool/courier/authdaemon

    ##NAME: DEBUG_LOGIN:0
    #
    # Set DEBUG_LOGIN to 1 to turn on authentication debugging (warning:
    # verbose logging).  Set DEBUG_LOGIN to 2 to turn on authentication
    # debugging as well as show all exchanged passwords in the logfile.
    # For obvious reasons DEBUG_LOGIN is turned off by default.

    DEBUG_LOGIN={{ userdb.debug_login | default("0") }}

    ##NAME: DEFAULTOPTIONS:0
    #
    # A comma-separated list of option=value pairs.  Each option is applied
    # to every authenticated user, unless the authenticated user has an
    # explicit setting that overrides it.
    #
    # Example: wantgid=65534,wantuid=65534,maildir=/home/mail,quota=100MB

    DEFAULTOPTIONS="{{ userdb.default_options | default("") }}"
  esmtpd-base-mta.template: |
    ##VERSION: $Id: 7543161d83cfd2206785e5bac11e78a43935e57e-20240610193431$
    #
    # Base esmtpd configuration for MTA service
    # Generated from template using context.json
    #

    PATH=/usr/lib/courier/bin:/bin:/usr/bin:/usr/local/bin
    SHELL=/bin/bash

    # Base syslog name
    SYSLOGNAME={{ mta.base_syslog_name | default("courieresmtpd") }}

    # Enable ESMTP daemon
    ESMTPDSTART=YES

    # Hide EXPN and VRFY commands
    BOFHNOEXPN=1
    BOFHNOVRFY=1

    # TLS protocol version
    TLS_PROTOCOL={{ mta.tls_protocol | default("TLSv1.2++") }}

    # Connection limits
    MAXDAEMONS={{ mta.max_daemons | default("40") }}
    MAXPERIP={{ mta.max_per_ip | default("4") }}
  esmtpd-base-mta-ssl.template: |
    ##VERSION: $Id: 7543161d83cfd2206785e5bac11e78a43935e57e-20240610193431$
    #
    # Base esmtpd configuration for MTA-SSL service
    # Generated from template using context.json
    #

    PATH=/usr/lib/courier/bin:/bin:/usr/bin:/usr/local/bin
    SHELL=/bin/bash

    # Base syslog name
    SYSLOGNAME={{ mta_ssl.base_syslog_name | default("courieresmtpd") }}

    # Enable ESMTP daemon
    ESMTPDSTART=YES

    # Hide EXPN and VRFY commands
    BOFHNOEXPN=1
    BOFHNOVRFY=1

    # TLS protocol version
    TLS_PROTOCOL={{ mta_ssl.tls_protocol | default("TLSv1.2++") }}

    # Connection limits
    MAXDAEMONS={{ mta_ssl.max_daemons | default("40") }}
    MAXPERIP={{ mta_ssl.max_per_ip | default("4") }}
  esmtpd-msa.template: |
    ##VERSION: $Id: 7543161d83cfd2206785e5bac11e78a43935e57e-20240610193431$
    #
    # esmtpd-msa configuration for MSA (Mail Submission Agent)
    # Generated from template using context.json
    #

    # MSA-specific syslog name
    SYSLOGNAME={{ msa.syslog_name | default("courieresmtpd-msa") }}

    # Enable ESMTP daemon
    ESMTPDSTART=YES

    # Authentication required for mail submission
    AUTH_REQUIRED=1

    # Disable DNS checks for faster submission
    BOFHCHECKDNS=0

    # TLS authentication methods
    ESMTPAUTH_TLS="{{ msa.auth_methods | default("PLAIN LOGIN CRAM-MD5 CRAM-SHA1 CRAM-SHA256") }}"

    # Enable detailed logging
    ESMTP_LOG_DIALOG={{ msa.log_level | default("2") }}
  esmtpd-mta.template: |
    ##VERSION: $Id: 7543161d83cfd2206785e5bac11e78a43935e57e-20240610193431$
    #
    # esmtpd configuration for MTA (Mail Transfer Agent)
    # Generated from template using context.json
    #

    PATH=/usr/lib/courier/bin:/bin:/usr/bin:/usr/local/bin
    SHELL=/bin/bash

    # MTA-specific syslog name
    SYSLOGNAME={{ mta.syslog_name | default("courieresmtpd-mta") }}

    # Enable ESMTP daemon
    ESMTPDSTART=YES

    # No authentication required for incoming mail
    AUTH_REQUIRED=0

    # Enable DNS checks for incoming mail
    BOFHCHECKDNS={{ mta.dns_checks | default("1") }}

    # Hide EXPN and VRFY commands
    BOFHNOEXPN=1
    BOFHNOVRFY=1

    # TLS authentication methods (optional for incoming)
    ESMTPAUTH_TLS="{{ mta.auth_methods | default("PLAIN LOGIN") }}"

    # TLS protocol version
    TLS_PROTOCOL={{ mta.tls_protocol | default("TLSv1.2++") }}

    # Connection limits
    MAXDAEMONS={{ mta.max_daemons | default("40") }}
    MAXPERIP={{ mta.max_per_ip | default("4") }}

    # TLS certificate files
    TLS_CERTFILE={{ mta.tls_certfile }}
    TLS_PRIVATE_KEYFILE={{ mta.tls_keyfile }}

    # Courier TLS binary location
    COURIERTLS=/usr/lib/courier/bin/couriertls
  esmtpd-mta-ssl.template: |
    ##VERSION: $Id: 7543161d83cfd2206785e5bac11e78a43935e57e-20240610193431$
    #
    # esmtpd configuration for MTA-SSL (SSL SMTP)
    # Generated from template using context.json
    #

    PATH=/usr/lib/courier/bin:/bin:/usr/bin:/usr/local/bin
    SHELL=/bin/bash

    # MTA-SSL-specific syslog name  
    SYSLOGNAME={{ mta_ssl.syslog_name | default("courieresmtpd-mta-ssl") }}

    # Enable ESMTP daemon
    ESMTPDSTART=YES

    # No authentication required for incoming mail
    AUTH_REQUIRED=0

    # Enable DNS checks for incoming mail
    BOFHCHECKDNS={{ mta_ssl.dns_checks | default("1") }}

    # Hide EXPN and VRFY commands
    BOFHNOEXPN=1
    BOFHNOVRFY=1

    # TLS authentication methods
    ESMTPAUTH_TLS="{{ mta_ssl.auth_methods | default("PLAIN LOGIN") }}"

    # TLS protocol version
    TLS_PROTOCOL={{ mta_ssl.tls_protocol | default("TLSv1.2++") }}

    # Connection limits
    MAXDAEMONS={{ mta_ssl.max_daemons | default("40") }}
    MAXPERIP={{ mta_ssl.max_per_ip | default("4") }}

    # TLS certificate files
    TLS_CERTFILE={{ mta_ssl.tls_certfile }}
    TLS_PRIVATE_KEYFILE={{ mta_ssl.tls_keyfile }}

    # Courier TLS binary location
    COURIERTLS=/usr/lib/courier/bin/couriertls
