apiVersion: v1
kind: ConfigMap
metadata:
  name: mailbag-context
  namespace: mailbag
data:
  context.json: |
    {
      "mda": {
        "mail_path_host": "/vmail/example.com",
        "mail_path_container": "/vmail/example.com",
        "owner": "300",
        "mode": "0755"
      },
      "mta": {
        "dns_name": "mail.example.com",
        "tls_certfile": "/certs/live/example.com/fullchain.pem",
        "tls_keyfile": "/certs/live/example.com/privkey.pem",
        "service": "courier-mta",
        "accept_mail_for": ["example.com"],
        "courierd_path_host": "/home/mailbag/spool/courier",
        "courierd_path_container": "/var/spool/courier"
      },
      "imapd_ssl": {
        "dns_name": "imap.example.com",
        "tls_certfile": "/certs/live/example.com/fullchain.pem",
        "tls_keyfile": "/certs/live/example.com/privkey.pem",
        "service": "courier-imapd-ssl"
      },
      "mta_ssl": {
        "dns_name": "smtp.example.com",
        "tls_certfile": "/certs/live/example.com/fullchain.pem",
        "tls_keyfile": "/certs/live/example.com/privkey.pem",
        "service": "courier-mta-ssl",
        "accept_mail_for": ["example.com"],
        "courierd_path_host": "/home/mailbag/spool/courier",
        "courierd_path_container": "/var/spool/courier"
      },
      "msa": {
        "dns_name": "mail.example.com",
        "tls_certfile": "/certs/live/example.com/fullchain.pem",
        "tls_keyfile": "/certs/live/example.com/privkey.pem",
        "service": "courier-msa",
        "courierd_path_host": "/home/mailbag/spool/courier",
        "courierd_path_container": "/var/spool/courier"
      },
      "userdb": {
        "directory": "/etc/authlib/userdb",
        "owner": "daemon",
        "mode": "0700"
      },
      "domain": {
        "name": "mail",
        "zone": "example.com"
      }
    }
  acceptmailfor.template: |
    {{ range .mta.accept_mail_for -}}
    {{.}}
    {{ end }}
  hosteddomains.template: |
    {{ range .mta.accept_mail_for -}}
    {{.}}
    {{ end }}
