apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: courier-mail-cert
  namespace: mailbag
spec:
  # Secret name where the certificate will be stored
  secretName: courier-mail-cert-tls
  # Reference to the ClusterIssuer
  issuerRef:
    name: letsencrypt-staging  # Start with staging for testing
    kind: ClusterIssuer
  # Common name for the certificate
  commonName: do-testmail.rton.me
  # Subject Alternative Names - All mail service hostnames
  dnsNames:
  - do-testmail.rton.me        # MTA (port 25)
  - mail.do-testmail.rton.me   # MSA (port 587)
  - smtp.do-testmail.rton.me   # MTA-SSL (port 465)
  - imap.do-testmail.rton.me   # IMAP-SSL (port 993)