apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: farout-mta-rton-me
  namespace: mailbag
spec:
  # Secret name where the certificate will be stored
  secretName: farout-mta-rton-me-tls
  # Reference to the ClusterIssuer
  issuerRef:
    name: letsencrypt-staging  # Start with staging for testing
    kind: ClusterIssuer
  # Common name for the certificate
  commonName: farout-mta.rton.me
  # Subject Alternative Names
  dnsNames:
  - farout-mta.rton.me
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: farout-imap-rton-me
  namespace: mailbag
spec:
  # Secret name where the certificate will be stored
  secretName: farout-imap-rton-me-tls
  # Reference to the ClusterIssuer
  issuerRef:
    name: letsencrypt-staging  # Start with staging for testing
    kind: ClusterIssuer
  # Common name for the certificate
  commonName: farout-imap.rton.me
  # Subject Alternative Names
  dnsNames:
  - farout-imap.rton.me