#!/bin/bash

set -e -x -o pipefail

# context.json is added via the docker/container as a bind mount
# /render-template --context /context.json --template /acceptmailfor.template > /etc/courier/esmtpacceptmailfor.dir/context
# /render-template --context /context.json --template /hosteddomains.template > /etc/courier/hosteddomains

# /usr/lib/courier/share/makehosteddomains

# # And start the msa, based on /usr/lib/courier/share/courierctl.start.
# we don't want to start this in the background
prefix="/usr/lib/courier"
exec_prefix="/usr/lib/courier"
sysconfdir="/etc/courier"
libexecdir="${exec_prefix}/libexec"

cd ${prefix}

/usr/bin/env -i /bin/bash -c "set -a ; . ${sysconfdir}/courierd; ${libexecdir}/courier/courierd "
