# TODO: use GITHUB_TOKEN to use a repository token instead of a PAT
# https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry

# This needs to be built once for the rest of the process to work, since from now on we're going to do the
# moral equivalent of
# docker run --entrypoint /export/render ghcr.io/pcn/pcn/mailbag-support:main
# in other words just get the binary from the registry

name: Build supporting artifacts and push them in container images
on:
  workflow_run:
    workflows:
      - release-please
    types:
      - completed


env:
  REGISTRY: ghcr.io
  NAMESPACE: pcn
  SUPPORT_IMAGE_NAME: ${{ github.repository }}-support
  PACKAGES_IMAGE_NAME: ${{ github.repository }}-packages
  BASE_IMAGE_NAME: ${{ github.repository }}-base
  

jobs:
  push_support_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository and build template 
        uses: actions/checkout@v4
      - name: build render-template
        uses: dtolnay/rust-toolchain@stable
        # Create the binary so the dockerfile can find it
      - run: make render-template

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.MAILBAG_ACTION_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.SUPPORT_IMAGE_NAME }}

      - name: Filter paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            renderer:
            - 'renderer/**'
            
      - name: Build and push the render binary
        uses: docker/build-push-action@v6
        id: build
        if: steps.changes.outputs.renderer == 'true'
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: support   # -${{ steps.meta.outputs.labels }}
          file: Dockerfile-support

  push_packages_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository and packages
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.MAILBAG_ACTION_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.PACKAGES_IMAGE_NAME }}

      - name: Filter paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            build-packages:
            - Dockerfile
            - install-scripts/**
            
      - name: Build and push the render binary
        uses: docker/build-push-action@v6
        id: build-packages
        if: steps.changes.outputs.renderer == 'true'
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: packages   # -${{ steps.meta.outputs.labels }}
          file: Dockerfile
          

  push_base_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository and push a base image
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.MAILBAG_ACTION_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}

      - name: Filter paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            renderer:
            - 'Dockerfile'
            - 'Dockerfile-base'
            - 'install-scripts/**'
            - 'entrypoints/**'
          
      - name: Build and push the base packages
        uses: docker/build-push-action@v6
        id: build
        if: steps.changes.outputs.renderer == 'true'
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: base   # -${{ steps.meta.outputs.labels }}
          file: Dockerfile-base
          
