name: Build supporting binaries and puh them
on:
  workflow_run:
    workflows:
      - release-please
    types:
      - completed


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-support

jobs:
  push_support_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository and build template tool
        uses: actions/checkout@v3
      - name: build render-template
        uses: dtolnay/rust-toolchain@stable
        # XXX fix the below
      - run: echo "foo" || make render-template

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.MAILBAG_ACTION_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}

      - name: Filter paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            renderer:
            - 'renderer/**'
            
      - name: Build and push the render binary
        uses: docker/build-push-action@v6
        id: build
        # if: steps.changes.outputs.renderer == 'true'
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: support   # -${{ steps.meta.outputs.labels }}
          file: Dockerfile-support
